namespace AIDevOpsCompany.Core.Models.QualityReports
{
    /// <summary>
    /// Represents efficiency-related metrics for quality reports and process improvement.
    /// </summary>
    public class EfficiencyMetrics
    {
        /// <summary>
        /// Overall productivity score.
        /// </summary>
        public double ProductivityScore { get; set; }
        /// <summary>
        /// Speed score for process/task completion.
        /// </summary>
        public double SpeedScore { get; set; }
        /// <summary>
        /// Score for how efficiently resources are utilized.
        /// </summary>
        public double ResourceUtilizationScore { get; set; }
        /// <summary>
        /// Score for cost efficiency in processes.
        /// </summary>
        public double CostEfficiencyScore { get; set; }
        /// <summary>
        /// Average response time for relevant operations.
        /// </summary>
        public TimeSpan AverageResponseTime { get; set; }
        /// <summary>
        /// Average processing time for tasks or requests.
        /// </summary>
        public TimeSpan AverageProcessingTime { get; set; }
        /// <summary>
        /// Rate of throughput (tasks/operations per unit time).
        /// </summary>
        public double ThroughputRate { get; set; }
        /// <summary>
        /// Percentage of processes that are automated.
        /// </summary>
        public double AutomationRate { get; set; }
        /// <summary>
        /// Number of process optimizations suggested.
        /// </summary>
        public int ProcessOptimizationsSuggested { get; set; }
        /// <summary>
        /// Number of process optimizations implemented.
        /// </summary>
        public int ProcessOptimizationsImplemented { get; set; }
        /// <summary>
        /// Total cost savings generated by improvements.
        /// </summary>
        public decimal CostSavingsGenerated { get; set; }
        /// <summary>
        /// Total value created by efficiency improvements.
        /// </summary>
        public decimal ValueCreated { get; set; }
    }
}
