namespace AIDevOpsCompany.Core.Models.Agents.Financials
{
    /// <summary>
    /// Represents financial metrics for an AI agent.
    /// </summary>
    public class AgentFinancials
    {
        /// <summary>
        /// Unique identifier for the agent.
        /// </summary>
        public string AgentId { get; set; } = string.Empty;
        /// <summary>
        /// Name of the agent.
        /// </summary>
        public string AgentName { get; set; } = string.Empty;
        /// <summary>
        /// Total revenue generated by the agent.
        /// </summary>
        public decimal RevenueGenerated { get; set; }
        /// <summary>
        /// Total costs incurred by the agent.
        /// </summary>
        public decimal CostsIncurred { get; set; }
        /// <summary>
        /// Profit contributed by the agent.
        /// </summary>
        public decimal ProfitContribution { get; set; }
        /// <summary>
        /// Utilization rate of the agent.
        /// </summary>
        public decimal UtilizationRate { get; set; }
        /// <summary>
        /// Efficiency score of the agent.
        /// </summary>
        public decimal EfficiencyScore { get; set; }
        /// <summary>
        /// Number of projects completed by the agent.
        /// </summary>
        public int ProjectsCompleted { get; set; }
        /// <summary>
        /// Average value of projects completed by the agent.
        /// </summary>
        public decimal AverageProjectValue { get; set; }
    }
}
