namespace AIDevOpsCompany.Core.Models.Agents.Performances
{
    /// <summary>
    /// Specifies the source of the feedback provided.
    /// </summary>
    public enum FeedbackSource
    {
        /// <summary>
        /// Feedback provided by a peer.
        /// </summary>
        Peer,
        /// <summary>
        /// Feedback provided by a supervisor or manager.
        /// </summary>
        Supervisor,
        /// <summary>
        /// Feedback provided by a client.
        /// </summary>
        Client,
        /// <summary>
        /// Feedback generated by the system.
        /// </summary>
        System,
        /// <summary>
        /// Feedback provided as a self-assessment.
        /// </summary>
        SelfAssessment,
        /// <summary>
        /// Feedback provided by a customer.
        /// </summary>
        Customer
    }
}
